# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:title
# https://help.github.com/articles/migrating-your-pages-site-from-maruku
markdown: kramdown

highlighter: pygments
paginate: 20 # pagination based on number of posts
paginate_path: "page/:num"

# These paths are to the main pages Jekyll-Bootstrap ships with.
# Some JB helpers refer to these paths; change them here if needed.
#
categories_path : categories.html
tags_path : tags.html

BASE_PATH : https://bashawesome.github.io/

title : $ Bash (Unix shell) Awesome V.0.0.1

author: 
  name: Lucas Gatsas 
  role: The Commandline and Git toolkit -List.
  email: lucasgatsas@gmail.com
  bio: "Simple, clean, $ Commandlines List for Mac Os X/ Unix & Linux! "
  commandlines: http://icons.iconarchive.com/icons/xenatt/the-circle/512/App-Terminal-icon.png
